cuda: True
n_points: 
n_classes: 
wandb: False
eval: False
visualize_pc: False

experiment:
  name: "Adapt_classf"
  project: "Adapt_reloaded"
  seed: 42
  dataset: "ModelNet40"

model:
  name: "Adapt_classf"
  embed_dim: 256
  n_blocks: 3
  drop_loc: [1,2]
  drop_rate: [0.5,0.75]
  groups: 4

train:
  lr: 0.001
  batch_size: 8
  epochs: 100
  weight_decay: 0.0001
  



