cuda: True
n_points: 
n_classes: 
wandb: True
eval: False
visualize_pc: False

experiment:
  name: "Adapt_classf"
  project: "Adapt_reloaded"
  seed: 42
  dataset: "ModelNet40"

model:
  name: "Adapt_classf"
  embed_dim: 256
  n_blocks: 5
  drop_loc: [1,2,3,4]
  drop_rate: [0.2,0.4,0.6,0.8]
  groups: 4
  sampling_met: "sparsemax"
  entmax_alpha: 

train:
  lr: 0.001
  batch_size: 32
  epochs: 200
  weight_decay: 0.0001
  warmup_start: 20
  warmup_end: 40
  alpha: 0.01
  

