cuda: True
n_points: 
n_classes: 
wandb: False
eval: False
visualize_pc: False

experiment:
  name: "PCT_reproduce"
  project: "Adapt_reloaded"
  seed: 42
  dataset: "ModelNet40"

model:
  name: "PCT_reproduce"
  embed_dim: 128
  n_blocks: 8
  drop_loc: [] #[1,3,5,7]
  drop_rate: [] #[0.2,0.4,0.6,0.8]
  groups: 4
  sampling_met: "gumbel"
  entmax_alpha: 


train:
  lr: 0.001
  batch_size: 1
  epochs: 200
  weight_decay: 0.0001
  warmup_start: 20
  warmup_end: 40
  alpha: 1
  n_budgets: 4

