name: std_sweep
project: AdaPT_reloaded
method: grid

metric:
  goal: maximize
  name: accuracy

parameters:
  - name: seed
    values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

command:
  - python
  - main.py
  - --seed
  - "{seed}"